#!/bin/bash

a_record() {
	name=$1
	address=$2
	zone=$3
	serial=$(cat /etc/bind/mrt-zones/db.$zone | grep -P 'Serial' | grep -oP '\d+')
	nextSerial=$(($serial + 1))

	# Add A record
	echo "$name	IN	A	$address" >> /etc/bind/mrt-zones/db.$zone;
	sed -i "s/$serial\t\t;\sSerial/$nextSerial\t\t; Serial/" /etc/bind/mrt-zones/db.$zone
	sudo systemctl restart named.service
}

cname_record() {
	echo "CNAME record"
}

mx_record() {
	echo "MX record"
}

t_option_used=false
while getopts ":t:" opt; do
	case $opt in
	t)
		record_type=$OPTARG
		t_option_used=true
		case $record_type in

			A)
				a_record "$3" "$4" "$5"
			;;

			CNAME)
				cname_record
			;;

			MX)
				mx_record
			;;

			*)
				echo "Invalid record type: $record_type"
				exit 1
			;;

		esac
	;;
	\?)
		echo "Invalid option: -$OPTARG"
		exit 1
	;;
	esac
done

if ! $t_option_used; then
	a_record
fi
