#!/bin/bash

stop() {
        iptables-restore /etc/iptables/stop.ipv4
        ip6tables-restore /etc/iptables/stop.ipv6
}

start() {
        iptables-restore /etc/iptables/start.ipv4
        ip6tables-restore /etc/iptables/start.ipv6

        sysctl -w net.ipv4.ip_forward=0
        sysctl -w net.ipv6.conf.all.forwarding=0
        sysctl -w net.ipv4.tcp_syncookies=1
}

case $1 in
        stop)
                stop
                ;;
        start)
                start
                ;;
        restart)
                stop
                start
                ;;
        *)
                exit 1;
esac
